LibClassicInspector attempt to mute CanInspect error speech
anzz1/TacoTip pull request #7
Opened 2022-10-12 12:48 UTC by ForestJ316

From testing it seems like msg appears first and then sound function runs so no race condition.

2022-10-13 00:20 UTC, perinazzoo commented
its working? @ForestJ316

2022-10-13 15:44 UTC, ForestJ316 commented
From what I tested, yes

2022-10-21 03:05 UTC, perinazzoo commented
@anzz1 any ETA to merge this?

2022-10-21 14:12 UTC, anzz1 commented
I can't test it right now, but I could merge it if you have tested it and there are no issues. @ForestJ316 @perinazzoo

2022-10-21 17:01 UTC, ForestJ316 commented
@anzz1 Been playing for a while and haven't noticed any issue so far. Wintergrasp seemed to be fine also, since I'm seeing a lot of ppl complaining about bgs triggering the error speech on curseforge comments. But I'm playing english locale. Doesn't seem like it should be an issue tho, unless blizzard decided to use different IDs for outofrange vocal errors on non-english locales?

2022-10-21 17:17 UTC, anzz1 commented
Very probably not, I would think constants such as that are indeed, constant. We'll see in the comments if that isn't the case then. :smile: 

What I'm more worried about is introducing taint, addon developers worst nemesis, which is the thing that causes those "Interface action failed because of an Addon" things which break the UI. Those kinds of pre-hooks can be dangerous since it taints the execution path that if an Blizzard function would call it and then do a "secure action", it could be blocked.

But such a thing like playing a error sound would probably happen at very tail-end of function execution and thus would not introduce taint, as was the case with the AddMessage hook.

Since you tested it and have had no problems, I can push it.

I'll get it merged this weekend and push an hotfix update. Thanks for your help !

2022-10-21 17:50 UTC, anzz1 requested changes
tabs to spaces

2022-10-21 17:50 UTC, anzz1 commented on Libs/LibClassicInspector/LibClassicInspector.lua
> +				skip_error = true
```suggestion
                skip_error = true
```

2022-10-21 17:50 UTC, anzz1 commented on Libs/LibClassicInspector/LibClassicInspector.lua
> +	if vocalErrorSoundID == 10 and skip_error == true then
```suggestion
    if vocalErrorSoundID == 10 and skip_error == true then
```

2022-10-21 17:50 UTC, anzz1 commented on Libs/LibClassicInspector/LibClassicInspector.lua
> +		skip_error = false
```suggestion
        skip_error = false
```

2022-10-21 17:50 UTC, anzz1 commented on Libs/LibClassicInspector/LibClassicInspector.lua
> +		return nil
```suggestion
        return nil
```

2022-10-21 17:50 UTC, anzz1 commented on Libs/LibClassicInspector/LibClassicInspector.lua
> +	end
```suggestion
    end
```

2022-10-21 17:50 UTC, anzz1 commented on Libs/LibClassicInspector/LibClassicInspector.lua
> +	return oPlayVocalErrorSoundID(vocalErrorSoundID, ...)
```suggestion
    return oPlayVocalErrorSoundID(vocalErrorSoundID, ...)
```

2022-10-21 18:22 UTC, merged

2022-10-21 18:43 UTC, anzz1 commented
Merged, released in 0.2.8 and pushed to addon channels. Thanks !